spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 990115
    database: 0
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedHeaders: "*" # 允许访问的头信息，*表示全部
            allowedOrigins: "*" # 跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        # 权限微服务
        - id: authorization
          uri: lb://authorization
          predicates:
            - Path=/auth/**
        # 系统微服务
        - id: system
          uri: lb://system
          predicates:
            - Path=/sys/**,/tag/**
        # 调度微服务
        - id: job
          uri: lb://job
          predicates:
            - Path=/job/**
        # 文章微服务
        - id: article
          uri: lb://article
          predicates:
            - Path=/article/**,/websocket/**
        # 文件微服务
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**